sudo: false

dist: xenial

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SUNphi
    - GH_REPO_REF: github.com/sunpho84/SUNphi.git
  matrix:
  - CC=clang CXX=clang++ THREADS=--enable-threads  MPI=--enable-MPI  DOXY=true
  - CC=clang CXX=clang++ THREADS=--enable-threads  MPI=--disable-MPI DOXY=false
  - CC=clang CXX=clang++ THREADS=--disable-threads MPI=--enable-MPI  DOXY=false
  - CC=clang CXX=clang++ THREADS=--disable-threads MPI=--disable-MPI DOXY=false
  - CC=gcc-8 CXX=g++-8   THREADS=--enable-threads  MPI=--enable-MPI  DOXY=false
  - CC=gcc-8 CXX=g++-8   THREADS=--enable-threads  MPI=--disable-MPI DOXY=false
  - CC=gcc-8 CXX=g++-8   THREADS=--disable-threads MPI=--enable-MPI  DOXY=false
  - CC=gcc-8 CXX=g++-8   THREADS=--disable-threads MPI=--disable-MPI DOXY=false

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - g++-8
      - libopenmpi-dev
      - clang
      - libclang1

script:
  - bash config/install_yaml_cpp.sh
  - bash config/bootstrap
  - mkdir build
  - cd build
  - ../configure $THREADS $MPI
  - cat config.log
  - make
  - bin/checks

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - rm -fr docs
  - which clang
  - clang --version
  - doxygen -v
  - make doxygen-run
  - cd $TRAVIS_BUILD_DIR
  - if [[ ! -z "$DOXY" ]] ;then . config/publishDocumentation.sh;fi
