sudo: false

# Blacklist
branches:
  except:
    - gh-pages

#compiler: clang

# Environment variables
env:
  global:
    - CC=gcc-7
    - CXX=g++-7
    - GH_REPO_NAME: SUNphi
    - GH_REPO_REF: github.com/sunpho84/SUNphi.git

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
#      - doxygen
#      - doxygen-doc
#      - doxygen-latex
#      - doxygen-gui
      - graphviz
      - g++-7
#      - clang-6.0
#      - libclang1-6.0

# install
install:
#   - cd /usr/lib/llvm-6.0/lib/
#   - ls -lrtha
#   - sudo ln -sf libclang-5.0.so.1 libclang.so.5
#   - cd -
#   - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/llvm-5.0/lib/
# installing doxygen
   - wget ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.src.tar.gz -O -|tar xzvf -
   - cd doxygen-1.8.14
   - mkdir build
   - cd build
   - cmake .. -Duse_libclang=ON
   - make
   - sudo make install
   - cd ../..
   - rm -fr doxygen-1.8.14

script:
  - bash config/bootstrap
  - mkdir build
  - cd build
  - ../configure
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - rm -fr docs
  - which clang
  - clang --version
  - doxygen -v
  - make doxygen-run
  - cd $TRAVIS_BUILD_DIR
  - . config/publishDocumentation.sh