# This will run on Travis' 'new' container-based infrastructure
sudo: false
# Blacklist
branches:
  except:
    - gh-pages

compiler: clang

# Environment variables
env:
  global:
    - CC=gcc-7
    - CXX=g++-7
    - GH_REPO_NAME: SUNphi
    - DOXYFILE: $TRAVIS_BUILD_DIR/build
    - GH_REPO_REF: github.com/sunpho84/SUNphi.git

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - g++-7

# Build your code e.g. by calling make
script:
  - bash config/bootstrap
  - mkdir build
  - cd build
  - ../configure
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - echo chmod +x generateDocumentationAndDeploy.sh
  - echo ./generateDocumentationAndDeploy.sh