# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

compiler: clang

# caching apt
cache:
  apt: true

# Environment variables
env:
  global:
    - CC=gcc-7
    - CXX=g++-7
    - GH_REPO_NAME: SUNphi
    - GH_REPO_REF: github.com/sunpho84/SUNphi.git

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
#      - doxygen
#      - doxygen-doc
#      - doxygen-latex
#      - doxygen-gui
      - graphviz
      - g++-7
#      - libclang1-5.0
#      - libxapian30
      
# installing doxygen
install:
   - wget ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.src.tar.gz -O -|tar xzvf -
   - cd doxygen-1.8.14
   - mkdir build
   - cd build
   - cmake .. -Duse_libclang=ON
   - make
   - sudo make install
   - cd ../..
   - rm -fr doxygen-1.8.14
   - doxygen -v

# Build your code e.g. by calling make
script:
  - bash config/bootstrap
  - mkdir build
  - cd build
  - ../configure
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/build
  - rm -fr docs
  - make doxygen-run
  - cd $TRAVIS_BUILD_DIR
  - . config/publishDocumentation.sh