var namespaceSUNphi =
[
    [ "_RelBindInternalChecks", "df/d7d/namespaceSUNphi_1_1__RelBindInternalChecks.html", "df/d7d/namespaceSUNphi_1_1__RelBindInternalChecks" ],
    [ "PairOfTensKindMergeability", "df/d08/namespaceSUNphi_1_1PairOfTensKindMergeability.html", null ],
    [ "IntSeq", "da/def/structSUNphi_1_1IntSeq.html", "da/def/structSUNphi_1_1IntSeq" ],
    [ "ConstrainIsOrderedIntSeq", "dd/dcd/structSUNphi_1_1ConstrainIsOrderedIntSeq.html", "dd/dcd/structSUNphi_1_1ConstrainIsOrderedIntSeq" ],
    [ "ConstrainIsOrderedUniqueIntSeq", "d3/dfa/structSUNphi_1_1ConstrainIsOrderedUniqueIntSeq.html", "d3/dfa/structSUNphi_1_1ConstrainIsOrderedUniqueIntSeq" ],
    [ "_IntSeqCat", "d0/d26/structSUNphi_1_1__IntSeqCat.html", null ],
    [ "_IntSeqCat< IntSeq< Ints...> >", "d1/da6/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints_8_8_8_4_01_4.html", "d1/da6/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints_8_8_8_4_01_4" ],
    [ "_IntSeqCat<>", "d6/db8/structSUNphi_1_1__IntSeqCat_3_4.html", "d6/db8/structSUNphi_1_1__IntSeqCat_3_4" ],
    [ "_IntSeqCat< IntSeq< Ints1...>, IntSeq< Ints2...>, T...>", "d7/d56/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints1_8_8_8_4_00_01IntSeq_3_01Ints2_8_8_8_4_00_01T_8_8_8_4.html", "d7/d56/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints1_8_8_8_4_00_01IntSeq_3_01Ints2_8_8_8_4_00_01T_8_8_8_4" ],
    [ "_IntSeqFirstN", "dc/dbf/structSUNphi_1_1__IntSeqFirstN.html", "dc/dbf/structSUNphi_1_1__IntSeqFirstN" ],
    [ "_IntSeqFilter", "dd/d69/structSUNphi_1_1__IntSeqFilter.html", null ],
    [ "_IntSeqFilter< IntSeq< Ints...>, IntSeq< Ids...> >", "d7/dd9/structSUNphi_1_1__IntSeqFilter_3_01IntSeq_3_01Ints_8_8_8_4_00_01IntSeq_3_01Ids_8_8_8_4_01_4.html", "d7/dd9/structSUNphi_1_1__IntSeqFilter_3_01IntSeq_3_01Ints_8_8_8_4_00_01IntSeq_3_01Ids_8_8_8_4_01_4" ],
    [ "_IntsUpTo", "dc/d02/structSUNphi_1_1__IntsUpTo.html", "dc/d02/structSUNphi_1_1__IntsUpTo" ],
    [ "_IntsUpTo< 0 >", "de/d18/structSUNphi_1_1__IntsUpTo_3_010_01_4.html", "de/d18/structSUNphi_1_1__IntsUpTo_3_010_01_4" ],
    [ "_IntsUpTo< 1 >", "d2/da7/structSUNphi_1_1__IntsUpTo_3_011_01_4.html", "d2/da7/structSUNphi_1_1__IntsUpTo_3_011_01_4" ],
    [ "_RangeSeq", "d0/dde/structSUNphi_1_1__RangeSeq.html", "d0/dde/structSUNphi_1_1__RangeSeq" ],
    [ "GridHashable", "dc/d35/classSUNphi_1_1GridHashable.html", null ],
    [ "GridHashable< T, NDims, Coord, Idx, true >", "d2/d37/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4.html", "d2/d37/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4" ],
    [ "GridHashable< T, NDims, Coord, Idx, false >", "dd/d4b/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4.html", "dd/d4b/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4" ],
    [ "Grid", "dd/dca/classSUNphi_1_1Grid.html", "dd/dca/classSUNphi_1_1Grid" ],
    [ "_EnableIf", "d5/d3d/structSUNphi_1_1__EnableIf.html", null ],
    [ "_EnableIf< true, T >", "d8/dd7/structSUNphi_1_1__EnableIf_3_01true_00_01T_01_4.html", "d8/dd7/structSUNphi_1_1__EnableIf_3_01true_00_01T_01_4" ],
    [ "ConstrainAreSame", "d2/d0b/classSUNphi_1_1ConstrainAreSame.html", null ],
    [ "_Conditional", "d3/de8/structSUNphi_1_1__Conditional.html", null ],
    [ "_Conditional< true, T, F >", "dd/db7/structSUNphi_1_1__Conditional_3_01true_00_01T_00_01F_01_4.html", "dd/db7/structSUNphi_1_1__Conditional_3_01true_00_01T_00_01F_01_4" ],
    [ "_Conditional< false, T, F >", "d6/d4d/structSUNphi_1_1__Conditional_3_01false_00_01T_00_01F_01_4.html", "d6/d4d/structSUNphi_1_1__Conditional_3_01false_00_01T_00_01F_01_4" ],
    [ "ConstrainIsBaseOf", "d1/d4c/structSUNphi_1_1ConstrainIsBaseOf.html", "d1/d4c/structSUNphi_1_1ConstrainIsBaseOf" ],
    [ "ConstrainIsNotBaseOf", "d6/d67/structSUNphi_1_1ConstrainIsNotBaseOf.html", "d6/d67/structSUNphi_1_1ConstrainIsNotBaseOf" ],
    [ "ConstrainNTypes", "d8/d4a/structSUNphi_1_1ConstrainNTypes.html", null ],
    [ "ConstrainIsFloatingPoint", "d1/d72/structSUNphi_1_1ConstrainIsFloatingPoint.html", null ],
    [ "ConstrainIsIntegral", "d8/d7e/structSUNphi_1_1ConstrainIsIntegral.html", null ],
    [ "ConstrainAreIntegrals", "d9/d8f/structSUNphi_1_1ConstrainAreIntegrals.html", null ],
    [ "Compl", "de/dee/structSUNphi_1_1Compl.html", "de/dee/structSUNphi_1_1Compl" ],
    [ "Dir", "da/dff/structSUNphi_1_1Dir.html", "da/dff/structSUNphi_1_1Dir" ],
    [ "Spacetime", "da/d14/structSUNphi_1_1Spacetime.html", "da/d14/structSUNphi_1_1Spacetime" ],
    [ "RwSpin", "dd/ded/structSUNphi_1_1RwSpin.html", "dd/ded/structSUNphi_1_1RwSpin" ],
    [ "CnSpin", "dd/d61/structSUNphi_1_1CnSpin.html", "dd/d61/structSUNphi_1_1CnSpin" ],
    [ "_TwinCompOf< RwSpin >", "df/dd7/structSUNphi_1_1__TwinCompOf_3_01RwSpin_01_4.html", "df/dd7/structSUNphi_1_1__TwinCompOf_3_01RwSpin_01_4" ],
    [ "_TwinCompOf< CnSpin >", "db/dd6/structSUNphi_1_1__TwinCompOf_3_01CnSpin_01_4.html", "db/dd6/structSUNphi_1_1__TwinCompOf_3_01CnSpin_01_4" ],
    [ "TwinTensCompOf< Spin >", "dc/d09/structSUNphi_1_1TwinTensCompOf_3_01Spin_01_4.html", "dc/d09/structSUNphi_1_1TwinTensCompOf_3_01Spin_01_4" ],
    [ "RwCol", "d8/dc9/structSUNphi_1_1RwCol.html", "d8/dc9/structSUNphi_1_1RwCol" ],
    [ "CnCol", "d0/da2/structSUNphi_1_1CnCol.html", "d0/da2/structSUNphi_1_1CnCol" ],
    [ "_TwinCompOf< RwCol >", "d6/ddd/structSUNphi_1_1__TwinCompOf_3_01RwCol_01_4.html", "d6/ddd/structSUNphi_1_1__TwinCompOf_3_01RwCol_01_4" ],
    [ "_TwinCompOf< CnCol >", "d3/da1/structSUNphi_1_1__TwinCompOf_3_01CnCol_01_4.html", "d3/da1/structSUNphi_1_1__TwinCompOf_3_01CnCol_01_4" ],
    [ "TwinTensCompOf< Col >", "d3/d3a/structSUNphi_1_1TwinTensCompOf_3_01Col_01_4.html", "d3/d3a/structSUNphi_1_1TwinTensCompOf_3_01Col_01_4" ],
    [ "Adder", "de/d58/classSUNphi_1_1Adder.html", "de/d58/classSUNphi_1_1Adder" ],
    [ "Assigner", "d4/d4b/classSUNphi_1_1Assigner.html", "d4/d4b/classSUNphi_1_1Assigner" ],
    [ "HasMember_name", "d3/d59/structSUNphi_1_1HasMember__name.html", "d3/d59/structSUNphi_1_1HasMember__name" ],
    [ "ConstrainHasMember_name", "d7/d1e/structSUNphi_1_1ConstrainHasMember__name.html", null ],
    [ "HasMember_eval", "d8/dfe/structSUNphi_1_1HasMember__eval.html", "d8/dfe/structSUNphi_1_1HasMember__eval" ],
    [ "ConstrainHasMember_eval", "dc/d20/structSUNphi_1_1ConstrainHasMember__eval.html", null ],
    [ "HasMember_isStoring", "d6/d8a/structSUNphi_1_1HasMember__isStoring.html", "d6/d8a/structSUNphi_1_1HasMember__isStoring" ],
    [ "ConstrainHasMember_isStoring", "db/d30/structSUNphi_1_1ConstrainHasMember__isStoring.html", null ],
    [ "HasMember_Tk", "d7/d03/structSUNphi_1_1HasMember__Tk.html", "d7/d03/structSUNphi_1_1HasMember__Tk" ],
    [ "ConstrainHasMember_Tk", "d0/db5/structSUNphi_1_1ConstrainHasMember__Tk.html", null ],
    [ "HasMember_Fund", "d2/d5d/structSUNphi_1_1HasMember__Fund.html", "d2/d5d/structSUNphi_1_1HasMember__Fund" ],
    [ "ConstrainHasMember_Fund", "d8/d7d/structSUNphi_1_1ConstrainHasMember__Fund.html", null ],
    [ "HasMember_isAliasing", "db/dc6/structSUNphi_1_1HasMember__isAliasing.html", "db/dc6/structSUNphi_1_1HasMember__isAliasing" ],
    [ "ConstrainHasMember_isAliasing", "d9/d02/structSUNphi_1_1ConstrainHasMember__isAliasing.html", null ],
    [ "HasMember_isAssignable", "dd/d8a/structSUNphi_1_1HasMember__isAssignable.html", "dd/d8a/structSUNphi_1_1HasMember__isAssignable" ],
    [ "ConstrainHasMember_isAssignable", "d4/d63/structSUNphi_1_1ConstrainHasMember__isAssignable.html", null ],
    [ "HasMember_MergeableComps", "d0/db2/structSUNphi_1_1HasMember__MergeableComps.html", "d0/db2/structSUNphi_1_1HasMember__MergeableComps" ],
    [ "ConstrainHasMember_MergeableComps", "d8/d32/structSUNphi_1_1ConstrainHasMember__MergeableComps.html", null ],
    [ "HasMember_assertMergeableWith", "d5/de5/structSUNphi_1_1HasMember__assertMergeableWith.html", "d5/de5/structSUNphi_1_1HasMember__assertMergeableWith" ],
    [ "ConstrainHasMember_assertMergeableWith", "d5/df6/structSUNphi_1_1ConstrainHasMember__assertMergeableWith.html", null ],
    [ "HasMember_getMergedCompsView", "d3/d4e/structSUNphi_1_1HasMember__getMergedCompsView.html", "d3/d4e/structSUNphi_1_1HasMember__getMergedCompsView" ],
    [ "ConstrainHasMember_getMergedCompsView", "d5/d33/structSUNphi_1_1ConstrainHasMember__getMergedCompsView.html", null ],
    [ "SmET", "d1/d31/structSUNphi_1_1SmET.html", "d1/d31/structSUNphi_1_1SmET" ],
    [ "BaseBinarySmET", "d2/d98/structSUNphi_1_1BaseBinarySmET.html", null ],
    [ "ConstrainAreBinarySmETs", "da/dce/structSUNphi_1_1ConstrainAreBinarySmETs.html", null ],
    [ "HasMember_ref1", "da/db5/structSUNphi_1_1HasMember__ref1.html", "da/db5/structSUNphi_1_1HasMember__ref1" ],
    [ "ConstrainHasMember_ref1", "d0/dd1/structSUNphi_1_1ConstrainHasMember__ref1.html", null ],
    [ "HasMember_ref2", "d3/d14/structSUNphi_1_1HasMember__ref2.html", "d3/d14/structSUNphi_1_1HasMember__ref2" ],
    [ "ConstrainHasMember_ref2", "d6/d5e/structSUNphi_1_1ConstrainHasMember__ref2.html", null ],
    [ "BinarySmET", "d4/d8b/structSUNphi_1_1BinarySmET.html", "d4/d8b/structSUNphi_1_1BinarySmET" ],
    [ "Binder", "d6/db9/classSUNphi_1_1Binder.html", "d6/db9/classSUNphi_1_1Binder" ],
    [ "Conjer", "d2/d24/classSUNphi_1_1Conjer.html", "d2/d24/classSUNphi_1_1Conjer" ],
    [ "MulAdder", "dc/d5d/classSUNphi_1_1MulAdder.html", "dc/d5d/classSUNphi_1_1MulAdder" ],
    [ "BaseNnarySmET", "d9/d67/structSUNphi_1_1BaseNnarySmET.html", null ],
    [ "ConstrainAreNnarySmETs", "d2/d10/structSUNphi_1_1ConstrainAreNnarySmETs.html", null ],
    [ "HasMember_refs", "dd/dce/structSUNphi_1_1HasMember__refs.html", "dd/dce/structSUNphi_1_1HasMember__refs" ],
    [ "ConstrainHasMember_refs", "d7/d12/structSUNphi_1_1ConstrainHasMember__refs.html", null ],
    [ "NnarySmET", "dc/d2f/structSUNphi_1_1NnarySmET.html", "dc/d2f/structSUNphi_1_1NnarySmET" ],
    [ "RelBinder", "d5/d1c/classSUNphi_1_1RelBinder.html", "d5/d1c/classSUNphi_1_1RelBinder" ],
    [ "ScalarWrapper", "db/d12/classSUNphi_1_1ScalarWrapper.html", "db/d12/classSUNphi_1_1ScalarWrapper" ],
    [ "Transposer", "d5/dd3/classSUNphi_1_1Transposer.html", "d5/dd3/classSUNphi_1_1Transposer" ],
    [ "UMinuser", "dd/d03/classSUNphi_1_1UMinuser.html", "dd/d03/classSUNphi_1_1UMinuser" ],
    [ "Wrapper", "d1/d77/classSUNphi_1_1Wrapper.html", "d1/d77/classSUNphi_1_1Wrapper" ],
    [ "_Indexer", "d7/da6/structSUNphi_1_1__Indexer.html", null ],
    [ "_Indexer< IDyn, TensKind< H, Oth...> >", "d9/d40/structSUNphi_1_1__Indexer_3_01IDyn_00_01TensKind_3_01H_00_01Oth_8_8_8_4_01_4.html", "d9/d40/structSUNphi_1_1__Indexer_3_01IDyn_00_01TensKind_3_01H_00_01Oth_8_8_8_4_01_4" ],
    [ "Tens", "d8/d1c/classSUNphi_1_1Tens.html", "d8/d1c/classSUNphi_1_1Tens" ],
    [ "TensComp", "d1/d96/structSUNphi_1_1TensComp.html", "d1/d96/structSUNphi_1_1TensComp" ],
    [ "HasMember_compSize", "de/d50/structSUNphi_1_1HasMember__compSize.html", "de/d50/structSUNphi_1_1HasMember__compSize" ],
    [ "ConstrainHasMember_compSize", "df/de8/structSUNphi_1_1ConstrainHasMember__compSize.html", null ],
    [ "ConstrainIsDynamic", "d4/de8/structSUNphi_1_1ConstrainIsDynamic.html", null ],
    [ "_TensKindFromTuple", "d8/d33/structSUNphi_1_1__TensKindFromTuple.html", null ],
    [ "_TensKindFromTuple< Tuple< Tp...> >", "da/ded/structSUNphi_1_1__TensKindFromTuple_3_01Tuple_3_01Tp_8_8_8_4_01_4.html", "da/ded/structSUNphi_1_1__TensKindFromTuple_3_01Tuple_3_01Tp_8_8_8_4_01_4" ],
    [ "TensKind", "d8/df8/classSUNphi_1_1TensKind.html", "d8/df8/classSUNphi_1_1TensKind" ],
    [ "_BlendTensKinds", "de/d12/structSUNphi_1_1__BlendTensKinds.html", null ],
    [ "_BlendTensKinds< Tk >", "df/dc7/structSUNphi_1_1__BlendTensKinds_3_01Tk_01_4.html", "df/dc7/structSUNphi_1_1__BlendTensKinds_3_01Tk_01_4" ],
    [ "_BlendTensKinds< Head1, Head2, Tail...>", "d1/dfc/structSUNphi_1_1__BlendTensKinds_3_01Head1_00_01Head2_00_01Tail_8_8_8_4.html", "d1/dfc/structSUNphi_1_1__BlendTensKinds_3_01Head1_00_01Head2_00_01Tail_8_8_8_4" ],
    [ "TensStor", "d3/d22/classSUNphi_1_1TensStor.html", "d3/d22/classSUNphi_1_1TensStor" ],
    [ "_TwinCompOf", "dd/d2a/structSUNphi_1_1__TwinCompOf.html", "dd/d2a/structSUNphi_1_1__TwinCompOf" ],
    [ "TwinTensCompOf", "d7/d08/structSUNphi_1_1TwinTensCompOf.html", null ],
    [ "_FilterVariadicList", "d0/d16/classSUNphi_1_1__FilterVariadicList.html", null ],
    [ "_FilterVariadicList< F, IntSeq< P...>, T...>", "d2/d07/classSUNphi_1_1__FilterVariadicList_3_01F_00_01IntSeq_3_01P_8_8_8_4_00_01T_8_8_8_4.html", "d2/d07/classSUNphi_1_1__FilterVariadicList_3_01F_00_01IntSeq_3_01P_8_8_8_4_00_01T_8_8_8_4" ],
    [ "_FilterVariadicClass", "d7/df6/classSUNphi_1_1__FilterVariadicClass.html", null ],
    [ "_FilterVariadicClass< F, V< List...> >", "dc/d16/classSUNphi_1_1__FilterVariadicClass_3_01F_00_01V_3_01List_8_8_8_4_01_4.html", "dc/d16/classSUNphi_1_1__FilterVariadicClass_3_01F_00_01V_3_01List_8_8_8_4_01_4" ],
    [ "IsNotNull", "d5/d4a/structSUNphi_1_1IsNotNull.html", "d5/d4a/structSUNphi_1_1IsNotNull" ],
    [ "IsNonNegative", "d8/d0c/structSUNphi_1_1IsNonNegative.html", "d8/d0c/structSUNphi_1_1IsNonNegative" ],
    [ "IsAlwaysTrue", "d4/d4b/structSUNphi_1_1IsAlwaysTrue.html", "d4/d4b/structSUNphi_1_1IsAlwaysTrue" ],
    [ "_isTuple", "d3/d6f/structSUNphi_1_1__isTuple.html", null ],
    [ "_isTuple< Tuple< Tp...> >", "d1/dd2/structSUNphi_1_1__isTuple_3_01Tuple_3_01Tp_8_8_8_4_01_4.html", null ],
    [ "ConstrainIsTuple", "df/de0/structSUNphi_1_1ConstrainIsTuple.html", null ],
    [ "ConstrainTupleTypesAreAllDifferent", "de/d1a/structSUNphi_1_1ConstrainTupleTypesAreAllDifferent.html", null ],
    [ "ConstrainTupleHasType", "d3/d4d/structSUNphi_1_1ConstrainTupleHasType.html", null ],
    [ "ConstrainTupleHasNotType", "df/d75/structSUNphi_1_1ConstrainTupleHasNotType.html", null ],
    [ "_TupleWrap", "d9/d27/structSUNphi_1_1__TupleWrap.html", "d9/d27/structSUNphi_1_1__TupleWrap" ],
    [ "_TupleWrap< Tuple< T...> >", "d7/de9/structSUNphi_1_1__TupleWrap_3_01Tuple_3_01T_8_8_8_4_01_4.html", "d7/de9/structSUNphi_1_1__TupleWrap_3_01Tuple_3_01T_8_8_8_4_01_4" ],
    [ "IsPresent", "dd/de6/structSUNphi_1_1IsPresent.html", "dd/de6/structSUNphi_1_1IsPresent" ],
    [ "IncapsulatedString", "da/d56/structSUNphi_1_1IncapsulatedString.html", "da/d56/structSUNphi_1_1IncapsulatedString" ]
];