#!/bin/sh

rm -fr \
    aclocal.m4 \
    autom4te.cache \
    $(find . -name "Makefile.in") \
    config/{compile,config.guess,config.sub,depcomp,install-sh,missing,ylwrap} \
    configure

autoreconf --verbose --install --force

mkdir -pv include/external
wget -O include/external/inplace_function.h https://raw.githubusercontent.com/WG21-SG14/SG14/master/SG14/inplace_function.h
