var annotated_dup =
[
    [ "SUNphi", null, [
      [ "_RelBindInternalChecks", "df/d7d/namespaceSUNphi_1_1__RelBindInternalChecks.html", "df/d7d/namespaceSUNphi_1_1__RelBindInternalChecks" ],
      [ "_BlendTensKinds", "de/d12/structSUNphi_1_1__BlendTensKinds.html", null ],
      [ "_BlendTensKinds< Head1, Head2, Tail... >", "de/d83/structSUNphi_1_1__BlendTensKinds_3_01Head1_00_01Head2_00_01Tail_8_8_8_01_4.html", "de/d83/structSUNphi_1_1__BlendTensKinds_3_01Head1_00_01Head2_00_01Tail_8_8_8_01_4" ],
      [ "_BlendTensKinds< Tk >", "df/dc7/structSUNphi_1_1__BlendTensKinds_3_01Tk_01_4.html", "df/dc7/structSUNphi_1_1__BlendTensKinds_3_01Tk_01_4" ],
      [ "_Conditional", "d3/de8/structSUNphi_1_1__Conditional.html", null ],
      [ "_Conditional< false, T, F >", "d6/d4d/structSUNphi_1_1__Conditional_3_01false_00_01T_00_01F_01_4.html", "d6/d4d/structSUNphi_1_1__Conditional_3_01false_00_01T_00_01F_01_4" ],
      [ "_Conditional< true, T, F >", "dd/db7/structSUNphi_1_1__Conditional_3_01true_00_01T_00_01F_01_4.html", "dd/db7/structSUNphi_1_1__Conditional_3_01true_00_01T_00_01F_01_4" ],
      [ "_EnableIf", "d5/d3d/structSUNphi_1_1__EnableIf.html", null ],
      [ "_EnableIf< true, T >", "d8/dd7/structSUNphi_1_1__EnableIf_3_01true_00_01T_01_4.html", "d8/dd7/structSUNphi_1_1__EnableIf_3_01true_00_01T_01_4" ],
      [ "_FilterVariadicClass", "d7/df6/classSUNphi_1_1__FilterVariadicClass.html", null ],
      [ "_FilterVariadicClass< F, V< List... > >", "d4/d3d/classSUNphi_1_1__FilterVariadicClass_3_01F_00_01V_3_01List_8_8_8_01_4_01_4.html", "d4/d3d/classSUNphi_1_1__FilterVariadicClass_3_01F_00_01V_3_01List_8_8_8_01_4_01_4" ],
      [ "_FilterVariadicList", "d0/d16/classSUNphi_1_1__FilterVariadicList.html", null ],
      [ "_FilterVariadicList< F, IntSeq< P... >, T... >", "dd/dae/classSUNphi_1_1__FilterVariadicList_3_01F_00_01IntSeq_3_01P_8_8_8_01_4_00_01T_8_8_8_01_4.html", "dd/dae/classSUNphi_1_1__FilterVariadicList_3_01F_00_01IntSeq_3_01P_8_8_8_01_4_00_01T_8_8_8_01_4" ],
      [ "_Indexer", "d7/da6/structSUNphi_1_1__Indexer.html", "d7/da6/structSUNphi_1_1__Indexer" ],
      [ "_Indexer< IDyn, TensKind< H, Oth... > >", "d7/d8b/structSUNphi_1_1__Indexer_3_01IDyn_00_01TensKind_3_01H_00_01Oth_8_8_8_01_4_01_4.html", "d7/d8b/structSUNphi_1_1__Indexer_3_01IDyn_00_01TensKind_3_01H_00_01Oth_8_8_8_01_4_01_4" ],
      [ "_IntSeqCat", "d0/d26/structSUNphi_1_1__IntSeqCat.html", null ],
      [ "_IntSeqCat< IntSeq< Ints... > >", "d2/d71/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints_8_8_8_01_4_01_4.html", "d2/d71/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints_8_8_8_01_4_01_4" ],
      [ "_IntSeqCat< IntSeq< Ints1... >, IntSeq< Ints2... >, T... >", "dc/d50/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints1_8_8_8_01_4_00_01IntSeq_3_01Ints2_8_8_8_01_4_00_01T_8_8_8_01_4.html", "dc/d50/structSUNphi_1_1__IntSeqCat_3_01IntSeq_3_01Ints1_8_8_8_01_4_00_01IntSeq_3_01Ints2_8_8_8_01_4_00_01T_8_8_8_01_4" ],
      [ "_IntSeqCat<>", "d6/db8/structSUNphi_1_1__IntSeqCat_3_4.html", "d6/db8/structSUNphi_1_1__IntSeqCat_3_4" ],
      [ "_IntSeqFilter", "dd/d69/structSUNphi_1_1__IntSeqFilter.html", null ],
      [ "_IntSeqFilter< IntSeq< Ints... >, IntSeq< Ids... > >", "d2/d71/structSUNphi_1_1__IntSeqFilter_3_01IntSeq_3_01Ints_8_8_8_01_4_00_01IntSeq_3_01Ids_8_8_8_01_4_01_4.html", "d2/d71/structSUNphi_1_1__IntSeqFilter_3_01IntSeq_3_01Ints_8_8_8_01_4_00_01IntSeq_3_01Ids_8_8_8_01_4_01_4" ],
      [ "_IntSeqFirstN", "dc/dbf/structSUNphi_1_1__IntSeqFirstN.html", "dc/dbf/structSUNphi_1_1__IntSeqFirstN" ],
      [ "_IntsUpTo", "dc/d02/structSUNphi_1_1__IntsUpTo.html", "dc/d02/structSUNphi_1_1__IntsUpTo" ],
      [ "_IntsUpTo< 0 >", "de/d18/structSUNphi_1_1__IntsUpTo_3_010_01_4.html", "de/d18/structSUNphi_1_1__IntsUpTo_3_010_01_4" ],
      [ "_IntsUpTo< 1 >", "d2/da7/structSUNphi_1_1__IntsUpTo_3_011_01_4.html", "d2/da7/structSUNphi_1_1__IntsUpTo_3_011_01_4" ],
      [ "_isTuple", "d3/d6f/structSUNphi_1_1__isTuple.html", null ],
      [ "_isTuple< Tuple< Tp... > >", "de/dff/structSUNphi_1_1__isTuple_3_01Tuple_3_01Tp_8_8_8_01_4_01_4.html", null ],
      [ "_RangeSeq", "d0/dde/structSUNphi_1_1__RangeSeq.html", "d0/dde/structSUNphi_1_1__RangeSeq" ],
      [ "_TensKindFromTuple", "d8/d33/structSUNphi_1_1__TensKindFromTuple.html", null ],
      [ "_TensKindFromTuple< Tuple< Tp... > >", "d7/dd1/structSUNphi_1_1__TensKindFromTuple_3_01Tuple_3_01Tp_8_8_8_01_4_01_4.html", "d7/dd1/structSUNphi_1_1__TensKindFromTuple_3_01Tuple_3_01Tp_8_8_8_01_4_01_4" ],
      [ "_TupleWrap", "d9/d27/structSUNphi_1_1__TupleWrap.html", "d9/d27/structSUNphi_1_1__TupleWrap" ],
      [ "_TupleWrap< Tuple< T... > >", "d6/d59/structSUNphi_1_1__TupleWrap_3_01Tuple_3_01T_8_8_8_01_4_01_4.html", "d6/d59/structSUNphi_1_1__TupleWrap_3_01Tuple_3_01T_8_8_8_01_4_01_4" ],
      [ "_TwinCompOf", "dd/d2a/structSUNphi_1_1__TwinCompOf.html", "dd/d2a/structSUNphi_1_1__TwinCompOf" ],
      [ "_TwinCompOf< CnCol >", "d3/da1/structSUNphi_1_1__TwinCompOf_3_01CnCol_01_4.html", "d3/da1/structSUNphi_1_1__TwinCompOf_3_01CnCol_01_4" ],
      [ "_TwinCompOf< CnSpin >", "db/dd6/structSUNphi_1_1__TwinCompOf_3_01CnSpin_01_4.html", "db/dd6/structSUNphi_1_1__TwinCompOf_3_01CnSpin_01_4" ],
      [ "_TwinCompOf< RwCol >", "d6/ddd/structSUNphi_1_1__TwinCompOf_3_01RwCol_01_4.html", "d6/ddd/structSUNphi_1_1__TwinCompOf_3_01RwCol_01_4" ],
      [ "_TwinCompOf< RwSpin >", "df/dd7/structSUNphi_1_1__TwinCompOf_3_01RwSpin_01_4.html", "df/dd7/structSUNphi_1_1__TwinCompOf_3_01RwSpin_01_4" ],
      [ "Adder", "de/d58/classSUNphi_1_1Adder.html", "de/d58/classSUNphi_1_1Adder" ],
      [ "Aliver", "df/df6/classSUNphi_1_1Aliver.html", "df/df6/classSUNphi_1_1Aliver" ],
      [ "Assigner", "d4/d4b/classSUNphi_1_1Assigner.html", "d4/d4b/classSUNphi_1_1Assigner" ],
      [ "BackTraceSymbol", "df/d4a/classSUNphi_1_1BackTraceSymbol.html", "df/d4a/classSUNphi_1_1BackTraceSymbol" ],
      [ "Barrier", "df/d49/structSUNphi_1_1Barrier.html", "df/d49/structSUNphi_1_1Barrier" ],
      [ "BaseAdder", "d6/d4b/structSUNphi_1_1BaseAdder.html", null ],
      [ "BaseAssigner", "dd/d4a/structSUNphi_1_1BaseAssigner.html", null ],
      [ "BaseBinarySmET", "d2/d98/structSUNphi_1_1BaseBinarySmET.html", null ],
      [ "BaseBinder", "da/db6/structSUNphi_1_1BaseBinder.html", null ],
      [ "BaseConjer", "d3/d04/structSUNphi_1_1BaseConjer.html", null ],
      [ "BaseIntSeq", "d2/d5c/structSUNphi_1_1BaseIntSeq.html", null ],
      [ "BaseMulAdder", "d2/dc3/structSUNphi_1_1BaseMulAdder.html", null ],
      [ "BaseNnarySmET", "d9/d67/structSUNphi_1_1BaseNnarySmET.html", null ],
      [ "BaseRelBinder", "da/d10/structSUNphi_1_1BaseRelBinder.html", null ],
      [ "BaseScalarWrapper", "d3/d7f/structSUNphi_1_1BaseScalarWrapper.html", null ],
      [ "BaseSmET", "d3/d5c/structSUNphi_1_1BaseSmET.html", null ],
      [ "BaseTens", "dc/dd0/structSUNphi_1_1BaseTens.html", null ],
      [ "BaseTensComp", "d1/d0d/structSUNphi_1_1BaseTensComp.html", null ],
      [ "BaseTensKind", "d4/dca/structSUNphi_1_1BaseTensKind.html", null ],
      [ "BaseTransposer", "df/ddf/structSUNphi_1_1BaseTransposer.html", null ],
      [ "BaseUMinuser", "d8/df3/structSUNphi_1_1BaseUMinuser.html", null ],
      [ "BaseWrapper", "d8/da7/structSUNphi_1_1BaseWrapper.html", null ],
      [ "BinarySmET", "d4/d8b/structSUNphi_1_1BinarySmET.html", "d4/d8b/structSUNphi_1_1BinarySmET" ],
      [ "Binder", "d6/db9/classSUNphi_1_1Binder.html", "d6/db9/classSUNphi_1_1Binder" ],
      [ "CanPrint", "de/dfd/structSUNphi_1_1CanPrint.html", "de/dfd/structSUNphi_1_1CanPrint" ],
      [ "CnCol", "d0/da2/structSUNphi_1_1CnCol.html", "d0/da2/structSUNphi_1_1CnCol" ],
      [ "CnSpin", "dd/d61/structSUNphi_1_1CnSpin.html", "dd/d61/structSUNphi_1_1CnSpin" ],
      [ "Combinatorial", "de/d33/classSUNphi_1_1Combinatorial.html", "de/d33/classSUNphi_1_1Combinatorial" ],
      [ "Compl", "de/dee/structSUNphi_1_1Compl.html", "de/dee/structSUNphi_1_1Compl" ],
      [ "Conjer", "d2/d24/classSUNphi_1_1Conjer.html", "d2/d24/classSUNphi_1_1Conjer" ],
      [ "ConstrainAreAdders", "df/d1f/structSUNphi_1_1ConstrainAreAdders.html", null ],
      [ "ConstrainAreAssigners", "d6/d43/structSUNphi_1_1ConstrainAreAssigners.html", null ],
      [ "ConstrainAreBinarySmETs", "da/dce/structSUNphi_1_1ConstrainAreBinarySmETs.html", null ],
      [ "ConstrainAreBinders", "d0/d5d/structSUNphi_1_1ConstrainAreBinders.html", null ],
      [ "ConstrainAreConjers", "d8/de3/structSUNphi_1_1ConstrainAreConjers.html", null ],
      [ "ConstrainAreIntegrals", "d9/d8f/structSUNphi_1_1ConstrainAreIntegrals.html", null ],
      [ "ConstrainAreIntSeqs", "d3/dab/structSUNphi_1_1ConstrainAreIntSeqs.html", null ],
      [ "ConstrainAreMulAdders", "df/ddd/structSUNphi_1_1ConstrainAreMulAdders.html", null ],
      [ "ConstrainAreNnarySmETs", "d2/d10/structSUNphi_1_1ConstrainAreNnarySmETs.html", null ],
      [ "ConstrainAreRelBinders", "d8/d9d/structSUNphi_1_1ConstrainAreRelBinders.html", null ],
      [ "ConstrainAreSame", "d2/d0b/classSUNphi_1_1ConstrainAreSame.html", null ],
      [ "ConstrainAreScalarWrappers", "d3/d3b/structSUNphi_1_1ConstrainAreScalarWrappers.html", null ],
      [ "ConstrainAreSmETs", "d1/de1/structSUNphi_1_1ConstrainAreSmETs.html", null ],
      [ "ConstrainAreTensComps", "d7/dfb/structSUNphi_1_1ConstrainAreTensComps.html", null ],
      [ "ConstrainAreTensKinds", "dc/d6d/structSUNphi_1_1ConstrainAreTensKinds.html", null ],
      [ "ConstrainAreTenss", "d8/dc0/structSUNphi_1_1ConstrainAreTenss.html", null ],
      [ "ConstrainAreTransposers", "d6/d62/structSUNphi_1_1ConstrainAreTransposers.html", null ],
      [ "ConstrainAreUMinusers", "d3/dde/structSUNphi_1_1ConstrainAreUMinusers.html", null ],
      [ "ConstrainAreWrappers", "d6/dbc/structSUNphi_1_1ConstrainAreWrappers.html", null ],
      [ "ConstrainHasMember_assertMergeableWith", "d5/df6/structSUNphi_1_1ConstrainHasMember__assertMergeableWith.html", null ],
      [ "ConstrainHasMember_binSize", "dc/d55/structSUNphi_1_1ConstrainHasMember__binSize.html", null ],
      [ "ConstrainHasMember_compSize", "df/de8/structSUNphi_1_1ConstrainHasMember__compSize.html", null ],
      [ "ConstrainHasMember_eval", "dc/d20/structSUNphi_1_1ConstrainHasMember__eval.html", null ],
      [ "ConstrainHasMember_Fund", "d8/d7d/structSUNphi_1_1ConstrainHasMember__Fund.html", null ],
      [ "ConstrainHasMember_getMergedCompsView", "d5/d33/structSUNphi_1_1ConstrainHasMember__getMergedCompsView.html", null ],
      [ "ConstrainHasMember_isAliasing", "d9/d02/structSUNphi_1_1ConstrainHasMember__isAliasing.html", null ],
      [ "ConstrainHasMember_isAssignable", "d4/d63/structSUNphi_1_1ConstrainHasMember__isAssignable.html", null ],
      [ "ConstrainHasMember_isStoring", "db/d30/structSUNphi_1_1ConstrainHasMember__isStoring.html", null ],
      [ "ConstrainHasMember_MergeableComps", "d8/d32/structSUNphi_1_1ConstrainHasMember__MergeableComps.html", null ],
      [ "ConstrainHasMember_name", "d7/d1e/structSUNphi_1_1ConstrainHasMember__name.html", null ],
      [ "ConstrainHasMember_ref1", "d0/dd1/structSUNphi_1_1ConstrainHasMember__ref1.html", null ],
      [ "ConstrainHasMember_ref2", "d6/d5e/structSUNphi_1_1ConstrainHasMember__ref2.html", null ],
      [ "ConstrainHasMember_refs", "d7/d12/structSUNphi_1_1ConstrainHasMember__refs.html", null ],
      [ "ConstrainHasMember_serializableMembers", "d3/da9/structSUNphi_1_1ConstrainHasMember__serializableMembers.html", null ],
      [ "ConstrainHasMember_Tk", "d0/db5/structSUNphi_1_1ConstrainHasMember__Tk.html", null ],
      [ "ConstrainIsBaseOf", "d1/d4c/structSUNphi_1_1ConstrainIsBaseOf.html", "d1/d4c/structSUNphi_1_1ConstrainIsBaseOf" ],
      [ "ConstrainIsDynamic", "d4/de8/structSUNphi_1_1ConstrainIsDynamic.html", null ],
      [ "ConstrainIsFloatingPoint", "d1/d72/structSUNphi_1_1ConstrainIsFloatingPoint.html", null ],
      [ "ConstrainIsIntegral", "d8/d7e/structSUNphi_1_1ConstrainIsIntegral.html", null ],
      [ "ConstrainIsNotBaseOf", "d6/d67/structSUNphi_1_1ConstrainIsNotBaseOf.html", "d6/d67/structSUNphi_1_1ConstrainIsNotBaseOf" ],
      [ "ConstrainIsOrderedIntSeq", "dd/dcd/structSUNphi_1_1ConstrainIsOrderedIntSeq.html", "dd/dcd/structSUNphi_1_1ConstrainIsOrderedIntSeq" ],
      [ "ConstrainIsOrderedUniqueIntSeq", "d3/dfa/structSUNphi_1_1ConstrainIsOrderedUniqueIntSeq.html", "d3/dfa/structSUNphi_1_1ConstrainIsOrderedUniqueIntSeq" ],
      [ "ConstrainIsTuple", "df/de0/structSUNphi_1_1ConstrainIsTuple.html", null ],
      [ "ConstrainNTypes", "d8/d4a/structSUNphi_1_1ConstrainNTypes.html", null ],
      [ "ConstrainTupleHasNotType", "df/d75/structSUNphi_1_1ConstrainTupleHasNotType.html", null ],
      [ "ConstrainTupleHasType", "d3/d4d/structSUNphi_1_1ConstrainTupleHasType.html", null ],
      [ "ConstrainTupleTypesAreAllDifferent", "de/d1a/structSUNphi_1_1ConstrainTupleTypesAreAllDifferent.html", null ],
      [ "Crasher", "db/de9/classSUNphi_1_1Crasher.html", "db/de9/classSUNphi_1_1Crasher" ],
      [ "CStringComparer", "d7/dcb/structSUNphi_1_1CStringComparer.html", "d7/dcb/structSUNphi_1_1CStringComparer" ],
      [ "DeSerializer", "dc/d7b/classSUNphi_1_1DeSerializer.html", "dc/d7b/classSUNphi_1_1DeSerializer" ],
      [ "Dir", "da/dff/structSUNphi_1_1Dir.html", "da/dff/structSUNphi_1_1Dir" ],
      [ "File", "d5/d99/classSUNphi_1_1File.html", "d5/d99/classSUNphi_1_1File" ],
      [ "Grid", "dd/dca/classSUNphi_1_1Grid.html", "dd/dca/classSUNphi_1_1Grid" ],
      [ "GridHashable", "dc/d35/classSUNphi_1_1GridHashable.html", null ],
      [ "GridHashable< T, NDims, Coord, Idx, false >", "dd/d4b/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4.html", "dd/d4b/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4" ],
      [ "GridHashable< T, NDims, Coord, Idx, true >", "d2/d37/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4.html", "d2/d37/classSUNphi_1_1GridHashable_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4" ],
      [ "GridShiftableBC", "df/da9/classSUNphi_1_1GridShiftableBC.html", null ],
      [ "GridShiftableBC< T, NDims, Coord, Idx, false >", "d4/dd1/classSUNphi_1_1GridShiftableBC_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4.html", "d4/dd1/classSUNphi_1_1GridShiftableBC_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01false_01_4" ],
      [ "GridShiftableBC< T, NDims, Coord, Idx, true >", "d5/def/classSUNphi_1_1GridShiftableBC_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4.html", "d5/def/classSUNphi_1_1GridShiftableBC_3_01T_00_01NDims_00_01Coord_00_01Idx_00_01true_01_4" ],
      [ "HasMember_assertMergeableWith", "d5/de5/structSUNphi_1_1HasMember__assertMergeableWith.html", "d5/de5/structSUNphi_1_1HasMember__assertMergeableWith" ],
      [ "HasMember_binSize", "df/d85/structSUNphi_1_1HasMember__binSize.html", "df/d85/structSUNphi_1_1HasMember__binSize" ],
      [ "HasMember_compSize", "de/d50/structSUNphi_1_1HasMember__compSize.html", "de/d50/structSUNphi_1_1HasMember__compSize" ],
      [ "HasMember_eval", "d8/dfe/structSUNphi_1_1HasMember__eval.html", "d8/dfe/structSUNphi_1_1HasMember__eval" ],
      [ "HasMember_Fund", "d2/d5d/structSUNphi_1_1HasMember__Fund.html", "d2/d5d/structSUNphi_1_1HasMember__Fund" ],
      [ "HasMember_getMergedCompsView", "d3/d4e/structSUNphi_1_1HasMember__getMergedCompsView.html", "d3/d4e/structSUNphi_1_1HasMember__getMergedCompsView" ],
      [ "HasMember_isAliasing", "db/dc6/structSUNphi_1_1HasMember__isAliasing.html", "db/dc6/structSUNphi_1_1HasMember__isAliasing" ],
      [ "HasMember_isAssignable", "dd/d8a/structSUNphi_1_1HasMember__isAssignable.html", "dd/d8a/structSUNphi_1_1HasMember__isAssignable" ],
      [ "HasMember_isStoring", "d6/d8a/structSUNphi_1_1HasMember__isStoring.html", "d6/d8a/structSUNphi_1_1HasMember__isStoring" ],
      [ "HasMember_MergeableComps", "d0/db2/structSUNphi_1_1HasMember__MergeableComps.html", "d0/db2/structSUNphi_1_1HasMember__MergeableComps" ],
      [ "HasMember_name", "d3/d59/structSUNphi_1_1HasMember__name.html", "d3/d59/structSUNphi_1_1HasMember__name" ],
      [ "HasMember_ref1", "da/db5/structSUNphi_1_1HasMember__ref1.html", "da/db5/structSUNphi_1_1HasMember__ref1" ],
      [ "HasMember_ref2", "d3/d14/structSUNphi_1_1HasMember__ref2.html", "d3/d14/structSUNphi_1_1HasMember__ref2" ],
      [ "HasMember_refs", "dd/dce/structSUNphi_1_1HasMember__refs.html", "dd/dce/structSUNphi_1_1HasMember__refs" ],
      [ "HasMember_serializableMembers", "d1/dbb/structSUNphi_1_1HasMember__serializableMembers.html", "d1/dbb/structSUNphi_1_1HasMember__serializableMembers" ],
      [ "HasMember_Tk", "d7/d03/structSUNphi_1_1HasMember__Tk.html", "d7/d03/structSUNphi_1_1HasMember__Tk" ],
      [ "IncapsulatedString", "da/d56/structSUNphi_1_1IncapsulatedString.html", "da/d56/structSUNphi_1_1IncapsulatedString" ],
      [ "IntSeq", "da/def/structSUNphi_1_1IntSeq.html", "da/def/structSUNphi_1_1IntSeq" ],
      [ "IsAlwaysTrue", "d4/d4b/structSUNphi_1_1IsAlwaysTrue.html", "d4/d4b/structSUNphi_1_1IsAlwaysTrue" ],
      [ "IsNonNegative", "d8/d0c/structSUNphi_1_1IsNonNegative.html", "d8/d0c/structSUNphi_1_1IsNonNegative" ],
      [ "IsNotNull", "d5/d4a/structSUNphi_1_1IsNotNull.html", "d5/d4a/structSUNphi_1_1IsNotNull" ],
      [ "IsPresent", "dd/de6/structSUNphi_1_1IsPresent.html", "dd/de6/structSUNphi_1_1IsPresent" ],
      [ "Logger", "d3/d78/classSUNphi_1_1Logger.html", "d3/d78/classSUNphi_1_1Logger" ],
      [ "MasterRandomGenerator", "d3/da1/classSUNphi_1_1MasterRandomGenerator.html", "d3/da1/classSUNphi_1_1MasterRandomGenerator" ],
      [ "Mpi", "df/d09/classSUNphi_1_1Mpi.html", "df/d09/classSUNphi_1_1Mpi" ],
      [ "MulAdder", "dc/d5d/classSUNphi_1_1MulAdder.html", "dc/d5d/classSUNphi_1_1MulAdder" ],
      [ "Mutex", "d6/d3d/structSUNphi_1_1Mutex.html", "d6/d3d/structSUNphi_1_1Mutex" ],
      [ "NnarySmET", "dc/d2f/structSUNphi_1_1NnarySmET.html", "dc/d2f/structSUNphi_1_1NnarySmET" ],
      [ "NoDefault", "d9/d2b/classSUNphi_1_1NoDefault.html", null ],
      [ "RelBinder", "d5/d1c/classSUNphi_1_1RelBinder.html", "d5/d1c/classSUNphi_1_1RelBinder" ],
      [ "RwCol", "d8/dc9/structSUNphi_1_1RwCol.html", "d8/dc9/structSUNphi_1_1RwCol" ],
      [ "RwSpin", "dd/ded/structSUNphi_1_1RwSpin.html", "dd/ded/structSUNphi_1_1RwSpin" ],
      [ "ScalarWrapper", "db/d12/classSUNphi_1_1ScalarWrapper.html", "db/d12/classSUNphi_1_1ScalarWrapper" ],
      [ "ScopeChangeVar", "d7/d0a/classSUNphi_1_1ScopeChangeVar.html", "d7/d0a/classSUNphi_1_1ScopeChangeVar" ],
      [ "ScopeDoer", "d2/db3/classSUNphi_1_1ScopeDoer.html", "d2/db3/classSUNphi_1_1ScopeDoer" ],
      [ "ScopeIndenter", "d3/d11/classSUNphi_1_1ScopeIndenter.html", "d3/d11/classSUNphi_1_1ScopeIndenter" ],
      [ "ScopeMutexLocker", "dd/db8/structSUNphi_1_1ScopeMutexLocker.html", null ],
      [ "SerializableClass", "d1/d39/classSUNphi_1_1SerializableClass.html", "d1/d39/classSUNphi_1_1SerializableClass" ],
      [ "SerializableDefaultValue", "dc/d2a/classSUNphi_1_1SerializableDefaultValue.html", "dc/d2a/classSUNphi_1_1SerializableDefaultValue" ],
      [ "SerializableDefaultValue< NoDefault >", "d7/dde/classSUNphi_1_1SerializableDefaultValue_3_01NoDefault_01_4.html", "d7/dde/classSUNphi_1_1SerializableDefaultValue_3_01NoDefault_01_4" ],
      [ "SerializableScalar", "d1/d97/classSUNphi_1_1SerializableScalar.html", "d1/d97/classSUNphi_1_1SerializableScalar" ],
      [ "Serializer", "d8/dd8/classSUNphi_1_1Serializer.html", "d8/dd8/classSUNphi_1_1Serializer" ],
      [ "SingleInstance", "db/d2f/classSUNphi_1_1SingleInstance.html", "db/d2f/classSUNphi_1_1SingleInstance" ],
      [ "Sitmo", "d9/d59/classSUNphi_1_1Sitmo.html", "d9/d59/classSUNphi_1_1Sitmo" ],
      [ "SmET", "d1/d31/structSUNphi_1_1SmET.html", "d1/d31/structSUNphi_1_1SmET" ],
      [ "Spacetime", "da/d14/structSUNphi_1_1Spacetime.html", "da/d14/structSUNphi_1_1Spacetime" ],
      [ "Tens", "d8/d1c/classSUNphi_1_1Tens.html", "d8/d1c/classSUNphi_1_1Tens" ],
      [ "TensComp", "d1/d96/structSUNphi_1_1TensComp.html", "d1/d96/structSUNphi_1_1TensComp" ],
      [ "TensKind", "d8/df8/classSUNphi_1_1TensKind.html", "d8/df8/classSUNphi_1_1TensKind" ],
      [ "TensStor", "d3/d22/classSUNphi_1_1TensStor.html", "d3/d22/classSUNphi_1_1TensStor" ],
      [ "Test", "dc/d39/classSUNphi_1_1Test.html", "dc/d39/classSUNphi_1_1Test" ],
      [ "Test2", "d9/d12/classSUNphi_1_1Test2.html", "d9/d12/classSUNphi_1_1Test2" ],
      [ "ThreadPool", "dc/d0f/classSUNphi_1_1ThreadPool.html", "dc/d0f/classSUNphi_1_1ThreadPool" ],
      [ "Timer", "d6/de9/classSUNphi_1_1Timer.html", "d6/de9/classSUNphi_1_1Timer" ],
      [ "Transposer", "d5/dd3/classSUNphi_1_1Transposer.html", "d5/dd3/classSUNphi_1_1Transposer" ],
      [ "TrueRandomGenerator", "d2/d95/classSUNphi_1_1TrueRandomGenerator.html", "d2/d95/classSUNphi_1_1TrueRandomGenerator" ],
      [ "TwinTensCompOf", "d7/d08/structSUNphi_1_1TwinTensCompOf.html", null ],
      [ "TwinTensCompOf< Col >", "d3/d3a/structSUNphi_1_1TwinTensCompOf_3_01Col_01_4.html", "d3/d3a/structSUNphi_1_1TwinTensCompOf_3_01Col_01_4" ],
      [ "TwinTensCompOf< Spin >", "dc/d09/structSUNphi_1_1TwinTensCompOf_3_01Spin_01_4.html", "dc/d09/structSUNphi_1_1TwinTensCompOf_3_01Spin_01_4" ],
      [ "UMinuser", "dd/d03/classSUNphi_1_1UMinuser.html", "dd/d03/classSUNphi_1_1UMinuser" ],
      [ "Vector", "df/dc0/classSUNphi_1_1Vector.html", "df/dc0/classSUNphi_1_1Vector" ],
      [ "Wrapper", "d1/d77/classSUNphi_1_1Wrapper.html", "d1/d77/classSUNphi_1_1Wrapper" ]
    ] ],
    [ "fuffa", "de/da3/classfuffa.html", "de/da3/classfuffa" ]
];